// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLgVFcPuxboyvB-adkWFugFfKIKfMOtqE',
    appId: '1:493781620027:web:fe7ec4b700df311fff931e',
    messagingSenderId: '493781620027',
    projectId: 'elevate-hub-6a053',
    authDomain: 'elevate-hub-6a053.firebaseapp.com',
    storageBucket: 'elevate-hub-6a053.firebasestorage.app',
    measurementId: 'G-T3EBB5WDYC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBfFnexkUbK_vS8lIemKkDmgu4msOWQlQ',
    appId: '1:493781620027:android:d46562e88c465ef0ff931e',
    messagingSenderId: '493781620027',
    projectId: 'elevate-hub-6a053',
    storageBucket: 'elevate-hub-6a053.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_15zbxpNLC7Ag1T8yAP9lsGCykE_IB-E',
    appId: '1:493781620027:ios:c8ebce4736ffed8eff931e',
    messagingSenderId: '493781620027',
    projectId: 'elevate-hub-6a053',
    storageBucket: 'elevate-hub-6a053.firebasestorage.app',
    iosBundleId: 'com.example.elevateHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_15zbxpNLC7Ag1T8yAP9lsGCykE_IB-E',
    appId: '1:493781620027:ios:c8ebce4736ffed8eff931e',
    messagingSenderId: '493781620027',
    projectId: 'elevate-hub-6a053',
    storageBucket: 'elevate-hub-6a053.firebasestorage.app',
    iosBundleId: 'com.example.elevateHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLgVFcPuxboyvB-adkWFugFfKIKfMOtqE',
    appId: '1:493781620027:web:daa85a677bf8b542ff931e',
    messagingSenderId: '493781620027',
    projectId: 'elevate-hub-6a053',
    authDomain: 'elevate-hub-6a053.firebaseapp.com',
    storageBucket: 'elevate-hub-6a053.firebasestorage.app',
    measurementId: 'G-HPW9HLSKW9',
  );
}
